/**
 * Sinh 22 mẫu văn bản (Phần III Sổ tay ban hành kèm QĐ 1966/QĐ-UBND ngày 05/8/2025) thành tệp
 * .docx có trường tự điền {…}. Nội dung theo Sổ tay (đã sửa lỗi chữ do chuyển đổi từ PDF);
 * thể thức theo NĐ 30/2020/NĐ-CP. Chạy lại: node tools/mau-van-ban/tao-mau.mjs
 *
 * Ghi chú VM-23: danh mục Phần III ghi Mẫu 14 = QĐ thu hồi đất, Mẫu 15 = QĐ phê duyệt phương án,
 * nhưng nội dung mẫu thực tế ngược lại. Phần mềm theo NỘI DUNG mẫu: 14 = QĐ phê duyệt PA, 15 = QĐ thu hồi.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { Packer, AlignmentType } from "docx";
import { P, giua, trai, lap, dauVanBan, quocHieu, tenVanBan, kyVanBan, kyBienBan, bangLap, thanhPhan, taoDocument } from "./khung.mjs";

const RA = new URL("../../apps/desktop/public/mau-van-ban/", import.meta.url);
mkdirSync(RA, { recursive: true });

const UBND_XA = ["ỦY BAN NHÂN DÂN", "{TEN_XA}"];
const DON_VI_BT = ["{CO_QUAN_CAP_TREN_BT}", "{TEN_DON_VI_BT}"];
const PHONG = ["ỦY BAN NHÂN DÂN {TEN_XA}", "{TEN_PHONG}"];
const CAN_CU = () => lap("can_cu", "{.}", { nghieng: true, sau: 60 });
const KET_BB = () => P("Biên bản kết thúc vào hồi {gio_ket_thuc} cùng ngày, các thành phần tham gia lập biên bản đã đọc, nhất trí với các nội dung trên đây và ký tên dưới đây./.");
const TP_DAY_DU = [
  ["Đại diện Ủy ban nhân dân {ten_xa}:", "tp_ubnd"],
  ["Đại diện Ủy ban Mặt trận Tổ quốc Việt Nam {ten_xa}:", "tp_mttq"],
  ["Đại diện đơn vị, tổ chức thực hiện nhiệm vụ bồi thường, giải phóng mặt bằng:", "tp_don_vi_bt"],
  ["Đại diện tổ/bản/khu dân cư:", "tp_ban"],
  ["Đại diện chủ đầu tư thực hiện dự án:", "tp_chu_dau_tu"],
];
const KY_DAY_DU = [
  "ĐẠI DIỆN UBND {TEN_XA}",
  "ĐẠI DIỆN ỦY BAN MTTQ VIỆT NAM\n{TEN_XA}",
  "ĐẠI DIỆN CHỦ ĐẦU TƯ",
  "ĐẠI DIỆN TỔ/BẢN/KHU DÂN CƯ",
  "ĐƠN VỊ, TỔ CHỨC THỰC HIỆN NHIỆM VỤ\nBỒI THƯỜNG, HỖ TRỢ, TÁI ĐỊNH CƯ",
  "CHỦ HỘ/NGƯỜI ĐẠI DIỆN\nHỘ GIA ĐÌNH, CÁ NHÂN/\nTỔ CHỨC CÓ ĐẤT THU HỒI",
];
const BANG_THUA = () =>
  bangLap("thua", [
    { tieuDe: "TT", truong: "stt", rong: 6 },
    { tieuDe: "Tờ bản đồ", truong: "so_to", rong: 12 },
    { tieuDe: "Thửa đất", truong: "so_thua", rong: 12 },
    { tieuDe: "Loại đất", truong: "loai_dat", rong: 12 },
    { tieuDe: "Diện tích thửa (m²)", truong: "dien_tich", rong: 18, canh: AlignmentType.RIGHT },
    { tieuDe: "Diện tích thu hồi (m²)", truong: "dt_thu_hoi", rong: 18, canh: AlignmentType.RIGHT, tong: "dt_thu_hoi_tong" },
    { tieuDe: "Ghi chú", truong: "pham_vi", rong: 22 },
  ]);
const BANG_DS_HO = () =>
  bangLap("ds_ho", [
    { tieuDe: "TT", truong: "stt", rong: 6 },
    { tieuDe: "Tên chủ sử dụng đất", truong: "ho_ten", rong: 28, canh: AlignmentType.LEFT },
    { tieuDe: "Địa chỉ", truong: "dia_chi", rong: 24, canh: AlignmentType.LEFT },
    { tieuDe: "Tờ, thửa", truong: "to_thua", rong: 18 },
    { tieuDe: "Loại đất", truong: "loai_dat", rong: 10 },
    { tieuDe: "DT thu hồi (m²)", truong: "dt_thu_hoi", rong: 14, canh: AlignmentType.RIGHT, tong: "tong_dt_thu_hoi" },
  ]);

const MAU = {
  "01": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/TB-UBND" }),
    ...tenVanBan("THÔNG BÁO THU HỒI ĐẤT", "Để thực hiện dự án {ten_du_an}"),
    ...CAN_CU(),
    P("Căn cứ tiến độ sử dụng đất thực hiện dự án {ten_du_an};", { nghieng: true }),
    P("Xét đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay},", { nghieng: true }),
    P("Chủ tịch Ủy ban nhân dân {ten_xa} thông báo như sau:"),
    P("**1. Thu hồi đất**"),
    P("Diện tích đất dự kiến thu hồi: {tong_dt_thu_hoi} m² (trường hợp đã hoàn thành trích đo, trích lục bản đồ địa chính thì ghi diện tích theo trích đo, trích lục)."),
    P("Địa điểm: {dia_diem_du_an}."),
    P("Tổng số hộ bị thu hồi đất, ảnh hưởng bởi dự án: {so_doi_tuong} (kèm theo danh sách chi tiết gồm: tên chủ sử dụng đất, diện tích thửa, tờ bản đồ số, loại đất)."),
    P("Diện tích thu hồi của {ho_ten} ({dia_chi}): {dt_thu_hoi} m², gồm:"),
    BANG_THUA(),
    P("Lý do thu hồi đất: {ly_do_thu_hoi}.", { truoc: 120 }),
    P("**2. Thời gian điều tra, khảo sát, đo đạc, kiểm đếm:** bắt đầu từ ngày {tg_dieu_tra_tu} đến ngày {tg_dieu_tra_den}."),
    P("**3. Hiệu lực thông báo thu hồi đất:** Thông báo này có hiệu lực 12 tháng tính từ ngày ban hành (đến ngày {tb_het_hieu_luc})."),
    P("**4. Dự kiến kế hoạch di chuyển, bố trí tái định cư:** {ke_hoach_tdc}."),
    P("Ông/bà (hoặc tổ chức) {ho_ten} có trách nhiệm phối hợp với {ten_don_vi_bt} thực hiện việc điều tra, khảo sát, đo đạc xác định diện tích đất, thống kê nhà ở, tài sản khác gắn liền với đất để lập phương án bồi thường, hỗ trợ, tái định cư./."),
    kyVanBan(),
  ],
  "02": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/TB-UBND" }),
    ...tenVanBan("THÔNG BÁO", "Kiểm kê hiện trạng"),
    ...CAN_CU(),
    P("Căn cứ tiến độ sử dụng đất thực hiện dự án {ten_du_an};", { nghieng: true }),
    P("Căn cứ Thông báo số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc thu hồi đất để thực hiện dự án {ten_du_an};", { nghieng: true }),
    P("Xét đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay},", { nghieng: true }),
    P("Chủ tịch Ủy ban nhân dân {ten_xa} thông báo như sau:"),
    P("1. {loai_doi_tuong}: {ho_ten}. Địa chỉ: {dia_chi}."),
    P("2. Thời gian tiến hành kiểm kê hiện trạng: từ {tg_kiem_ke_tu} đến {tg_kiem_ke_den}."),
    P("Ông/bà/người đại diện tổ chức {ho_ten} có trách nhiệm phối hợp với {ten_don_vi_bt} trong thời gian tiến hành kiểm kê hiện trạng quy định trên đây."),
    P("Trường hợp ông/bà/người đại diện tổ chức không chấp hành thì bị kiểm đếm bắt buộc theo quy định của pháp luật./."),
    kyVanBan(),
  ],
  "03": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("TỜ TỰ KHAI", "Về đất và tài sản có trên đất Nhà nước thu hồi\nđể thực hiện dự án {ten_du_an}"),
    giua("Kính gửi: Ủy ban nhân dân {ten_xa}", { truoc: 120 }),
    P("Tôi tên là: {ho_ten}, là người đại diện cho {loai_doi_tuong_thuong} {ho_ten}."),
    P("Địa chỉ: {dia_chi}."),
    P("Thực hiện Thông báo số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc thu hồi đất để thực hiện dự án {ten_du_an}."),
    P("Sau khi nghe đại diện {ten_don_vi_bt} cung cấp, phổ biến và giải thích rõ về các căn cứ pháp lý cho việc thu hồi đất, thực hiện bồi thường, giải phóng mặt bằng dự án {ten_du_an}, chúng tôi xin tự kê khai về đất và tài sản trên thửa đất đang sử dụng trong khu vực thực hiện dự án như sau:"),
    P("**1. Về đất**"),
    P("Giấy chứng nhận quyền sử dụng đất số {so_gcn} do {co_quan_cap_gcn} cấp, thời điểm cấp {ngay_cap_gcn}. Tên người được cấp giấy chứng nhận: {ten_tren_gcn}."),
    P("Các giấy tờ khác có liên quan đến việc sử dụng đất gồm: {giay_to_dat}."),
    BANG_THUA(),
    P("- Nguồn gốc sử dụng: {nguon_goc};", { truoc: 120 }),
    P("- Thời điểm sử dụng: {thoi_diem_su_dung};"),
    P("- Các thông tin khác có liên quan: {thong_tin_khac}."),
    P("**2. Về tài sản trên đất**"),
    P("- Loại nhà cửa, công trình, vật kiến trúc, cây cối hoa màu, tài sản trên đất:"),
    bangLap("tai_san", [
      { tieuDe: "TT", truong: "stt", rong: 6 },
      { tieuDe: "Tài sản", truong: "ten", rong: 52, canh: AlignmentType.LEFT },
      { tieuDe: "ĐVT", truong: "dvt", rong: 10 },
      { tieuDe: "Khối lượng / số lượng", truong: "khoi_luong", rong: 16, canh: AlignmentType.RIGHT },
      { tieuDe: "Thửa", truong: "thua", rong: 16 },
    ]),
    P("- Giấy tờ có liên quan đến việc sử dụng tài sản: {giay_to_tai_san}.", { truoc: 120 }),
    P("Tôi xin cam đoan những nội dung trên đây là đúng sự thực và hoàn toàn chịu trách nhiệm trước pháp luật về những thông tin đã cung cấp./."),
    kyBienBan([null, "CHỦ HỘ/NGƯỜI ĐẠI DIỆN HỘ GIA ĐÌNH,\nCÁ NHÂN/ĐẠI DIỆN TỔ CHỨC\nCÓ ĐẤT THU HỒI"], "(Ký, ghi rõ họ tên và đóng dấu nếu có)"),
  ],
  "04": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN KIỂM ĐẾM", "Về đất và tài sản có trên đất Nhà nước thu hồi\nđể thực hiện dự án {ten_du_an}"),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, chúng tôi gồm:", { truoc: 120 }),
    P("**I. THÀNH PHẦN THAM GIA**"),
    ...thanhPhan([
      ["Đại diện đơn vị, tổ chức thực hiện nhiệm vụ bồi thường, giải phóng mặt bằng:", "tp_don_vi_bt"],
      ["Đại diện Ủy ban nhân dân {ten_xa}:", "tp_ubnd"],
      ["Đại diện bản/khu dân cư:", "tp_ban"],
      ["Hộ gia đình/cá nhân/tổ chức có đất, tài sản trên đất Nhà nước thu hồi:", "tp_nguoi_co_dat"],
      ["Các thành phần khác có liên quan (nếu có):", "tp_khac"],
    ]),
    P("**II. KẾT QUẢ**"),
    P("Chúng tôi đã cùng nhau làm việc kiểm kê về đất và tài sản có trên đất do {ho_ten} đang sử dụng, trong khu vực Nhà nước thu hồi để thực hiện dự án {ten_du_an}, kết quả như sau:"),
    P("**1. Về đất**"),
    P("Tên người được cấp giấy chứng nhận: {ten_tren_gcn}. Địa chỉ: {dia_chi}."),
    P("Các giấy tờ khác có liên quan đến việc sử dụng đất gồm: {giay_to_dat}."),
    BANG_THUA(),
    P("Nguồn gốc sử dụng: {nguon_goc}. Thời điểm sử dụng: {thoi_diem_su_dung}. Các thông tin khác có liên quan: {thong_tin_khac}.", { truoc: 120 }),
    P("**2. Về tài sản trên đất**"),
    bangLap("tai_san", [
      { tieuDe: "TT", truong: "stt", rong: 6 },
      { tieuDe: "Loại nhà cửa, công trình, vật kiến trúc, cây cối hoa màu", truong: "ten", rong: 48, canh: AlignmentType.LEFT },
      { tieuDe: "ĐVT", truong: "dvt", rong: 10 },
      { tieuDe: "Khối lượng / số lượng", truong: "khoi_luong", rong: 16, canh: AlignmentType.RIGHT },
      { tieuDe: "Thửa", truong: "thua", rong: 10 },
      { tieuDe: "Đợt", truong: "dot", rong: 10 },
    ]),
    P("- Giấy tờ có liên quan đến việc sử dụng tài sản: {giay_to_tai_san}.", { truoc: 120 }),
    P("- Các thông tin khác có liên quan: {thong_tin_tai_san}."),
    KET_BB(),
    kyBienBan([
      "ĐƠN VỊ, TỔ CHỨC THỰC HIỆN NHIỆM VỤ\nBỒI THƯỜNG, HỖ TRỢ, TÁI ĐỊNH CƯ",
      "ĐẠI DIỆN UBND {TEN_XA}",
      "XÁC NHẬN CỦA TRƯỞNG\nBẢN/KHU DÂN CƯ",
      "CHỦ HỘ/NGƯỜI ĐẠI DIỆN\nHỘ GIA ĐÌNH, CÁ NHÂN/\nTỔ CHỨC CÓ ĐẤT THU HỒI",
    ]),
  ],
  "05": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN", "Về việc tuyên truyền, vận động, thuyết phục người sử dụng đất phối hợp\nđiều tra, khảo sát, đo đạc, kiểm đếm khi Nhà nước thu hồi đất\nđể thực hiện dự án {ten_du_an}"),
    P("Căn cứ Thông báo số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc thu hồi đất để thực hiện dự án {ten_du_an};", { nghieng: true, truoc: 120 }),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, thực hiện tuyên truyền, vận động, thuyết phục người sử dụng đất phối hợp điều tra, khảo sát, đo đạc, kiểm đếm, chúng tôi gồm:"),
    P("**I. THÀNH PHẦN THAM GIA**"),
    ...thanhPhan([...TP_DAY_DU, ["Các thành phần khác có liên quan (nếu có):", "tp_khac"]]),
    P("**II. NỘI DUNG**"),
    P("Chúng tôi đã cung cấp và giải thích rõ cho ông/bà {ho_ten} các chính sách pháp luật hiện hành về thu hồi đất, bồi thường, hỗ trợ, tái định cư và các quy định có liên quan."),
    P("Chúng tôi vận động ông/bà {ho_ten} là đại diện cho {loai_doi_tuong_thuong} có đất, tài sản trên đất Nhà nước thu hồi đồng thuận, phối hợp với cơ quan Nhà nước có thẩm quyền để thực hiện công tác điều tra, khảo sát, đo đạc, kiểm đếm."),
    P("**III. KẾT QUẢ**"),
    P("Sau khi nghe giải thích của các bên có liên quan, ông/bà {ho_ten} có ý kiến như sau: {y_kien}."),
    KET_BB(),
    kyBienBan(KY_DAY_DU),
  ],
  "06": () => quyetDinhKiemDem(false),
  "07": () => quyetDinhKiemDem(true),
  "08": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN", "Về việc lấy ý kiến tham gia về phương án bồi thường, hỗ trợ\nvà tái định cư dự án {ten_du_an}"),
    P("Căn cứ Thông báo thu hồi đất số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về thu hồi đất để thực hiện dự án {ten_du_an};", { nghieng: true, truoc: 120 }),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, {ten_don_vi_bt} phối hợp với Ủy ban nhân dân {ten_xa} tổ chức hội nghị lấy ý kiến về phương án bồi thường, hỗ trợ và tái định cư khi Nhà nước thu hồi đất thực hiện dự án {ten_du_an}."),
    P("**I. THÀNH PHẦN**"),
    ...thanhPhan([
      ...TP_DAY_DU,
      ["Người có đất đai, tài sản gắn liền với đất, người có quyền lợi, nghĩa vụ liên quan (liệt kê đầy đủ hoặc lập danh sách kèm theo biên bản):", "tp_nguoi_co_dat"],
      ["Các thành phần khác có liên quan (nếu có):", "tp_khac"],
    ]),
    P("**II. NỘI DUNG**"),
    P("1. Sau khi nghe đại diện {ten_don_vi_bt} và đại diện Ủy ban nhân dân {ten_xa} trình bày chi tiết dự thảo phương án bồi thường, hỗ trợ và tái định cư khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}, người có đất và tài sản trên đất Nhà nước thu hồi đã phát biểu các ý kiến như sau: {y_kien}."),
    P("2. Ý kiến giải thích, giải trình hoặc tiếp thu của đơn vị, tổ chức làm nhiệm vụ bồi thường, giải phóng mặt bằng và đại diện Ủy ban nhân dân {ten_xa}: {giai_trinh}."),
    P("3. Sau khi nghe giải thích của các bên có liên quan, có ý kiến như sau: {y_kien_sau}."),
    P("**III. KẾT QUẢ**"),
    P("Số lượng ý kiến đồng ý: {so_dong_y}; số lượng ý kiến không đồng ý: {so_khong_dong_y}; số lượng ý kiến khác: {so_y_kien_khac} đối với phương án bồi thường, hỗ trợ, tái định cư; nội dung tiếp thu, giải trình: {tiep_thu}."),
    KET_BB(),
    kyBienBan(KY_DAY_DU.slice(0, 5)),
  ],
  "09": () => niemYet(false),
  "10": () => niemYet(true),
  "11": () => [
    dauVanBan({ coQuan: DON_VI_BT, so: "Số: {so}/TTr-{ky_hieu_don_vi}" }),
    ...tenVanBan("TỜ TRÌNH", "Về việc đề nghị thẩm định phương án bồi thường, hỗ trợ, tái định cư\nkhi Nhà nước thu hồi đất thực hiện dự án {ten_du_an}"),
    giua("Kính gửi: {co_quan_tham_dinh}.", { truoc: 120 }),
    ...CAN_CU(),
    P("{ten_don_vi_bt} trình thẩm định phương án bồi thường, hỗ trợ, tái định cư dự án {ten_du_an} với những nội dung cụ thể như sau:"),
    ...noiDungPhuongAn({ cho: "11" }),
    P("(Có phương án bồi thường, hỗ trợ và tái định cư chi tiết kèm theo)", { nghieng: true, canh: AlignmentType.CENTER, thut: 0 }),
    P("Vậy {ten_don_vi_bt} đề nghị {co_quan_tham_dinh} xem xét, thẩm định./."),
    kyVanBan(),
  ],
  "12": () => [
    dauVanBan({ coQuan: PHONG, so: "Số: {so}/TTr-{ky_hieu_phong}" }),
    ...tenVanBan("TỜ TRÌNH", "Về việc đề nghị thu hồi đất để thực hiện dự án {ten_du_an}"),
    giua("Kính gửi: Chủ tịch Ủy ban nhân dân {ten_xa}.", { truoc: 120 }),
    ...CAN_CU(),
    P("{ten_phong} đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} thu hồi đất để thực hiện dự án {ten_du_an}, cụ thể như sau:"),
    P("**1.** Thu hồi {tong_dt_thu_hoi} m² đất của {so_doi_tuong} tổ chức, hộ gia đình, cá nhân (có danh sách chi tiết kèm theo)."),
    P("Địa điểm: {dia_diem_du_an}."),
    P("Lý do thu hồi đất: {ly_do_thu_hoi} (ghi rõ mục đích thu hồi đất theo quy định tại Điều 78, Điều 79 Luật Đất đai)."),
    P("**2.** Giao nhiệm vụ cho các cơ quan, tổ chức thực hiện việc thu hồi đất, cụ thể như sau:"),
    P("2.1. {ten_phong} có trách nhiệm: niêm yết công khai quyết định thu hồi đất tại trụ sở Ủy ban nhân dân {ten_xa} và tại nơi sinh hoạt chung của khu dân cư; giao quyết định thu hồi đất cho tổ chức, hộ gia đình, cá nhân tại điểm 1; trường hợp vắng mặt hoặc không nhận quyết định thì phải lập biên bản."),
    P("2.2. {co_quan_dang_tai} có trách nhiệm đăng tải quyết định thu hồi đất trên trang thông tin điện tử của Ủy ban nhân dân {ten_xa}."),
    P("2.3. Giao {co_quan_quan_ly_dat} quản lý chặt chẽ diện tích đất đã thu hồi."),
    P("Đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} xem xét, quyết định./."),
    kyVanBan(),
    giua("DANH SÁCH CHI TIẾT KÈM THEO", { dam: true, truoc: 240 }),
    BANG_DS_HO(),
  ],
  "13": () => [
    dauVanBan({ coQuan: PHONG, so: "Số: {so}/TTr-{ky_hieu_phong}" }),
    ...tenVanBan("TỜ TRÌNH", "Về việc đề nghị phê duyệt phương án bồi thường, hỗ trợ, tái định cư\nkhi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}"),
    giua("Kính gửi: Chủ tịch Ủy ban nhân dân {ten_xa}.", { truoc: 120 }),
    ...CAN_CU(),
    P("Căn cứ kết quả thẩm định phương án bồi thường, hỗ trợ, tái định cư tại {ket_qua_tham_dinh};", { nghieng: true }),
    P("{ten_phong} đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} phê duyệt phương án bồi thường, hỗ trợ, tái định cư để thực hiện dự án {ten_du_an}, với các nội dung cụ thể như sau:"),
    ...noiDungPhuongAn({ cho: "13" }),
    P("(Có phương án bồi thường, hỗ trợ và tái định cư chi tiết kèm theo)", { nghieng: true, canh: AlignmentType.CENTER, thut: 0 }),
    P("Đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} xem xét, quyết định./."),
    kyVanBan(),
  ],
  "14": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/QĐ-UBND" }),
    ...tenVanBan("QUYẾT ĐỊNH", "Về việc phê duyệt phương án bồi thường, hỗ trợ, tái định cư\nkhi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}"),
    giua("CHỦ TỊCH ỦY BAN NHÂN DÂN {TEN_XA}", { dam: true, truoc: 120 }),
    ...CAN_CU(),
    P("Theo đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay}.", { nghieng: true }),
    giua("QUYẾT ĐỊNH:", { dam: true, truoc: 120 }),
    P("**Điều 1.** Phê duyệt phương án bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}, cụ thể như sau:"),
    ...noiDungPhuongAn({ cho: "14" }),
    P("(Có phương án bồi thường, hỗ trợ và tái định cư chi tiết kèm theo)", { nghieng: true, canh: AlignmentType.CENTER, thut: 0 }),
    P("**Điều 2.** Nhiệm vụ, trách nhiệm của các bên có liên quan:"),
    P("1. {ten_don_vi_bt} có trách nhiệm phối hợp với chủ đầu tư dự án, {ten_phong} và Ủy ban nhân dân {ten_xa} nơi có đất Nhà nước thu hồi phổ biến và niêm yết công khai quyết định này; giao quyết định này đến từng tổ chức, hộ gia đình, cá nhân; trường hợp tổ chức, hộ gia đình, cá nhân không nhận quyết định này hoặc vắng mặt thì phải lập biên bản."),
    P("2. {ten_don_vi_bt} có trách nhiệm phối hợp với các cơ quan có liên quan chi trả tiền bồi thường, hỗ trợ, tái định cư theo phương án được phê duyệt trong thời hạn 30 ngày kể từ ngày quyết định này có hiệu lực."),
    P("3. Văn phòng {co_quan_dang_tai} có trách nhiệm đăng tải quyết định này trên trang thông tin điện tử của Ủy ban nhân dân {ten_xa}."),
    P("**Điều 3.** Quyết định này có hiệu lực kể từ ngày {ngay_hieu_luc}."),
    P("**Điều 4.** {co_quan_thi_hanh}, Ủy ban nhân dân {ten_xa} nơi có đất Nhà nước thu hồi và các tổ chức, hộ gia đình, cá nhân có tên trong phương án bồi thường, hỗ trợ, tái định cư chịu trách nhiệm thi hành Quyết định này./."),
    kyVanBan(),
  ],
  "15": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/QĐ-UBND" }),
    ...tenVanBan("QUYẾT ĐỊNH", "Về việc thu hồi đất"),
    giua("CHỦ TỊCH ỦY BAN NHÂN DÂN {TEN_XA}", { dam: true, truoc: 120 }),
    ...CAN_CU(),
    P("Theo đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay}.", { nghieng: true }),
    giua("QUYẾT ĐỊNH:", { dam: true, truoc: 120 }),
    P("**Điều 1.** Thu hồi {dt_thu_hoi} m² đất của {ho_ten}, thuộc {thua_mo_ta}, tại {ten_xa}, tỉnh Sơn La."),
    P("Lý do thu hồi đất: {ly_do_thu_hoi}."),
    P("**Điều 2.** Giao nhiệm vụ cho các cơ quan, tổ chức thực hiện việc thu hồi đất, cụ thể như sau:"),
    P("1. {ten_phong} có trách nhiệm giao quyết định này cho ông (bà) {ho_ten}; trường hợp ông (bà) {ho_ten} không nhận quyết định này hoặc vắng mặt thì phải lập biên bản; niêm yết quyết định này tại trụ sở Ủy ban nhân dân {ten_xa} và tại nơi sinh hoạt chung của khu dân cư {ban_khu_dan_cu}."),
    P("2. Văn phòng Ủy ban nhân dân {ten_xa} có trách nhiệm đăng tải quyết định này trên trang thông tin điện tử của Ủy ban nhân dân {ten_xa}."),
    P("3. {ten_don_vi_bt} có trách nhiệm quản lý quỹ đất đã thu hồi, phối hợp với {co_quan_quan_ly_dat} thực hiện các thủ tục theo quy định."),
    P("**Điều 3.**"),
    P("1. Quyết định này có hiệu lực kể từ ngày {ngay_hieu_luc}."),
    P("2. Tổ chức, cá nhân có tên tại Điều 2 nêu trên chịu trách nhiệm thi hành Quyết định này./."),
    kyVanBan(),
  ],
  "16": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN", "Bàn giao {ten_quyet_dinh_giao}"),
    P("Căn cứ Quyết định số {qd_giao_so} ngày {qd_giao_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc {qd_giao_trich_yeu};", { nghieng: true, truoc: 120 }),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, chúng tôi gồm:"),
    ...thanhPhan([
      ["Đại diện Ủy ban nhân dân {ten_xa}:", "tp_ubnd"],
      ["Đại diện đơn vị, tổ chức thực hiện nhiệm vụ bồi thường, giải phóng mặt bằng:", "tp_don_vi_bt"],
      ["Đại diện tổ chức/hộ gia đình/cá nhân:", "tp_nguoi_co_dat"],
      ["Các thành phần khác (nếu có):", "tp_khac"],
    ]),
    P("Chúng tôi đã tiến hành giao Quyết định số {qd_giao_so} ngày {qd_giao_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc {qd_giao_trich_yeu} cho ông (bà) {ho_ten} là đại diện tổ chức, hộ gia đình, cá nhân có đất Nhà nước thu hồi (hoặc có tài sản trên đất)."),
    P("Đề nghị ông (bà) {ho_ten} đúng {tg_nhan_tien} có mặt tại {dia_diem_nhan_tien} để nhận tiền bồi thường, hỗ trợ giải phóng mặt bằng."),
    P("Sau thời gian {so_ngay_ban_giao} ngày kể từ ngày ông (bà) nhận đủ số tiền bồi thường, hỗ trợ và tái định cư, đề nghị ông (bà) thu dọn tài sản trên đất để bàn giao mặt bằng cho {ben_nhan_mat_bang} để thực hiện dự án."),
    P("Biên bản kết thúc vào hồi {gio_ket_thuc} cùng ngày, đại diện các bên nhất trí ký tên dưới đây./."),
    kyBienBan(["BÊN GIAO", "BÊN NHẬN"]),
  ],
  "17": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN", "Về việc tuyên truyền, vận động người sử dụng đất nhận tiền bồi thường,\nhỗ trợ và bàn giao mặt bằng (lần thứ {lan_thu})"),
    P("Căn cứ Quyết định số {qd_thu_hoi_so} ngày {qd_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc thu hồi đất để thực hiện dự án {ten_du_an}; Quyết định số {qd_phe_duyet_so} ngày {qd_phe_duyet_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc phê duyệt phương án bồi thường, hỗ trợ và tái định cư khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an};", { nghieng: true, truoc: 120 }),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}. Nội dung cụ thể như sau:"),
    P("**I. THÀNH PHẦN THAM GIA**"),
    ...thanhPhan([...TP_DAY_DU, ["Các thành phần khác có liên quan (nếu có):", "tp_khac"]]),
    P("**II. NỘI DUNG**"),
    P("Chúng tôi đã cung cấp và giải thích rõ cho ông/bà {ho_ten} các chính sách pháp luật hiện hành về thu hồi đất, bồi thường, hỗ trợ, tái định cư và các quy định có liên quan."),
    P("Chúng tôi vận động ông/bà {ho_ten} là đại diện cho {loai_doi_tuong_thuong} có đất, tài sản trên đất Nhà nước thu hồi tự giác chấp hành quyết định thu hồi đất, nhận tiền bồi thường, hỗ trợ ({tong_tien} đồng) và bàn giao mặt bằng."),
    P("Nếu ông/bà {ho_ten} không tự giác chấp hành thì bị cưỡng chế theo quy định của pháp luật."),
    P("**III. KẾT QUẢ**"),
    P("Sau khi nghe ý kiến giải thích và vận động của các cơ quan có liên quan, ông/bà {ho_ten} có ý kiến như sau: {y_kien}."),
    KET_BB(),
    kyBienBan(KY_DAY_DU),
  ],
  "18": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/TB-UBND" }),
    ...tenVanBan("THÔNG BÁO", "Về việc gửi tiền bồi thường, hỗ trợ vào tài khoản tiền gửi của đơn vị,\ntổ chức thực hiện nhiệm vụ bồi thường, hỗ trợ, tái định cư"),
    P("Căn cứ Quyết định số {qd_phe_duyet_so} ngày {qd_phe_duyet_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc phê duyệt phương án bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}.", { truoc: 120 }),
    P("Ủy ban nhân dân {ten_xa} đã phối hợp với Ủy ban Mặt trận Tổ quốc Việt Nam {ten_xa} và {ten_don_vi_bt} tuyên truyền, vận động {so_lan_van_dong} lần nhưng không nhận được sự đồng thuận của {ho_ten}."),
    P("Nay thông báo tiền bồi thường, hỗ trợ của {ho_ten} là {tong_tien} đồng (bằng chữ: {tong_tien_chu}) đã được chuyển toàn bộ vào tài khoản tiền gửi của {ten_don_vi_bt} số {so_tai_khoan} tại {ngan_hang}."),
    P("Vậy xin thông báo để được biết./."),
    kyVanBan(),
  ],
  "19": () => [
    ...quocHieu({ ngay: true }),
    ...tenVanBan("BIÊN BẢN", "Bàn giao Thông báo việc gửi tiền bồi thường, hỗ trợ vào tài khoản tiền gửi\ncủa đơn vị, tổ chức thực hiện nhiệm vụ bồi thường, hỗ trợ, tái định cư"),
    P("Căn cứ Quyết định số {qd_phe_duyet_so} ngày {qd_phe_duyet_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc phê duyệt phương án bồi thường, hỗ trợ và tái định cư khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}.", { nghieng: true, truoc: 120 }),
    P("Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, chúng tôi gồm:"),
    P("**I. THÀNH PHẦN THAM GIA**"),
    ...thanhPhan([
      ["Đại diện Ủy ban nhân dân {ten_xa}:", "tp_ubnd"],
      ["Đại diện đơn vị, tổ chức thực hiện nhiệm vụ bồi thường, giải phóng mặt bằng:", "tp_don_vi_bt"],
      ["Đại diện tổ/bản/khu dân cư:", "tp_ban"],
      ["Đại diện chủ đầu tư thực hiện dự án:", "tp_chu_dau_tu"],
      ["Các thành phần khác có liên quan (nếu có):", "tp_khac"],
    ]),
    P("**II. NỘI DUNG**"),
    P("Tiến hành bàn giao Thông báo số {tb_gui_tien_so} ngày {tb_gui_tien_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc gửi tiền bồi thường, hỗ trợ của {ho_ten} ({tong_tien} đồng) vào tài khoản tiền gửi của {ten_don_vi_bt}."),
    P("Biên bản kết thúc vào hồi {gio_ket_thuc} cùng ngày, đại diện các bên nhất trí ký tên dưới đây./."),
    kyBienBan(["BÊN GIAO", "BÊN NHẬN", "ĐẠI DIỆN CHỦ ĐẦU TƯ", "CÁC THÀNH PHẦN KHÁC"]),
  ],
  "20": () => [
    dauVanBan({ coQuan: PHONG, so: "Số: {so}/TTr-{ky_hieu_phong}" }),
    ...tenVanBan("TỜ TRÌNH", "Về việc đề nghị phê duyệt danh sách các hộ gia đình, cá nhân đủ điều kiện\nnhận hỗ trợ và mức hỗ trợ bàn giao mặt bằng sớm (khuyến khích tiến độ)\nkhi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}"),
    giua("Kính gửi: Chủ tịch Ủy ban nhân dân {ten_xa}.", { truoc: 120 }),
    ...CAN_CU(),
    P("Căn cứ Biên bản niêm yết công khai và Biên bản kết thúc niêm yết công khai danh sách các hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ và mức hỗ trợ bàn giao mặt bằng sớm {bb_niem_yet_thuong};", { nghieng: true }),
    P("{ten_phong} đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} phê duyệt danh sách các hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ và mức hỗ trợ bàn giao mặt bằng sớm, như sau:"),
    P("1. Tổng số hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ: {so_ho_thuong} hộ."),
    P("2. Tổng số tiền hỗ trợ: {tong_tien_thuong} đồng (bằng chữ: {tong_tien_thuong_chu})."),
    P("(Có danh sách chi tiết các hộ gia đình, cá nhân đủ điều kiện hỗ trợ và mức hỗ trợ bàn giao mặt bằng kèm theo)", { nghieng: true }),
    P("Đề nghị Chủ tịch Ủy ban nhân dân {ten_xa} xem xét, quyết định./."),
    kyVanBan(),
    giua("DANH SÁCH KÈM THEO", { dam: true, truoc: 240 }),
    BANG_THUONG(),
  ],
  "21": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/QĐ-UBND" }),
    ...tenVanBan("QUYẾT ĐỊNH", "Về việc phê duyệt danh sách các hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ\nvà mức hỗ trợ bàn giao mặt bằng sớm (khuyến khích tiến độ)\nkhi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}"),
    giua("CHỦ TỊCH ỦY BAN NHÂN DÂN {TEN_XA}", { dam: true, truoc: 120 }),
    ...CAN_CU(),
    P("Xét đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay}.", { nghieng: true }),
    giua("QUYẾT ĐỊNH:", { dam: true, truoc: 120 }),
    P("**Điều 1.** Phê duyệt danh sách các hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ và mức hỗ trợ bàn giao mặt bằng sớm (khuyến khích tiến độ) khi Nhà nước thu hồi đất để thực hiện dự án {ten_du_an}, như sau:"),
    P("1. Tổng số hộ gia đình, cá nhân đủ điều kiện nhận hỗ trợ: {so_ho_thuong} hộ."),
    P("2. Tổng số tiền hỗ trợ: {tong_tien_thuong} đồng (bằng chữ: {tong_tien_thuong_chu})."),
    P("(Có danh sách chi tiết các hộ gia đình, cá nhân đủ điều kiện hỗ trợ và mức hỗ trợ bàn giao mặt bằng kèm theo)", { nghieng: true }),
    P("**Điều 2.**"),
    P("1. {ten_don_vi_bt} giao quyết định này đến từng hộ gia đình, cá nhân; trường hợp hộ gia đình, cá nhân không nhận quyết định này hoặc vắng mặt thì phải lập biên bản; tổ chức việc niêm yết công khai quyết định này theo quy định."),
    P("2. {ten_don_vi_bt} phối hợp với Ủy ban nhân dân {ten_xa} và các đơn vị có liên quan chi trả tiền tại Điều 1 quyết định này theo quy định."),
    P("3. Văn phòng Ủy ban nhân dân {ten_xa} có trách nhiệm đăng tải quyết định này trên trang thông tin điện tử của Ủy ban nhân dân {ten_xa}."),
    P("**Điều 3.**"),
    P("1. Quyết định này có hiệu lực kể từ ngày {ngay_hieu_luc}."),
    P("2. {co_quan_thi_hanh} và các tổ chức, hộ gia đình, cá nhân có tên trong danh sách tại Điều 1 chịu trách nhiệm thi hành Quyết định này./."),
    kyVanBan(),
    giua("DANH SÁCH KÈM THEO", { dam: true, truoc: 240 }),
    BANG_THUONG(),
  ],
  "22": () => [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/QĐ-UBND" }),
    ...tenVanBan("QUYẾT ĐỊNH", "Về việc cưỡng chế thu hồi đất"),
    giua("CHỦ TỊCH ỦY BAN NHÂN DÂN {TEN_XA}", { dam: true, truoc: 120 }),
    ...CAN_CU(),
    P("Căn cứ Quyết định số {qd_thu_hoi_so} ngày {qd_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc thu hồi đất;", { nghieng: true }),
    P("Xét đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay}.", { nghieng: true }),
    giua("QUYẾT ĐỊNH:", { dam: true, truoc: 120 }),
    P("**Điều 1.** Áp dụng biện pháp cưỡng chế thu hồi đất đối với {ho_ten}, thuộc {thua_mo_ta}, tại {ten_xa}, tỉnh Sơn La."),
    P("Thời gian thực hiện cưỡng chế thu hồi đất từ ngày {tg_cuong_che_tu} đến ngày {tg_cuong_che_den}."),
    P("**Điều 2.**"),
    P("1. Quyết định này có hiệu lực kể từ ngày {ngay_hieu_luc}."),
    P("2. {ten_phong} có trách nhiệm giao quyết định này cho {ho_ten} và niêm yết công khai quyết định này tại trụ sở Ủy ban nhân dân {ten_xa}, địa điểm sinh hoạt chung của khu dân cư {ban_khu_dan_cu}."),
    P("3. Giao {co_quan_cuong_che} triển khai thực hiện cưỡng chế thu hồi đất theo quy định của pháp luật."),
    P("4. Kinh phí phục vụ thực hiện cưỡng chế: {kinh_phi_cuong_che}."),
    P("5. {co_quan_thi_hanh} và {ho_ten} chịu trách nhiệm thi hành Quyết định này./."),
    kyVanBan(),
  ],
};

function BANG_THUONG() {
  return bangLap("ds_thuong", [
    { tieuDe: "TT", truong: "stt", rong: 6 },
    { tieuDe: "Họ và tên", truong: "ho_ten", rong: 30, canh: AlignmentType.LEFT },
    { tieuDe: "Địa chỉ", truong: "dia_chi", rong: 28, canh: AlignmentType.LEFT },
    { tieuDe: "Ngày bàn giao mặt bằng", truong: "ngay_ban_giao", rong: 16 },
    { tieuDe: "Mức hỗ trợ (đồng)", truong: "muc_ho_tro", rong: 20, canh: AlignmentType.RIGHT, tong: "tong_tien_thuong" },
  ]);
}

function quyetDinhKiemDem(cuongChe) {
  return [
    dauVanBan({ coQuan: UBND_XA, so: "Số: {so}/QĐ-UBND" }),
    ...tenVanBan("QUYẾT ĐỊNH", cuongChe ? "Về việc cưỡng chế thực hiện quyết định kiểm đếm bắt buộc" : "Về việc kiểm đếm bắt buộc"),
    giua("CHỦ TỊCH ỦY BAN NHÂN DÂN {TEN_XA}", { dam: true, truoc: 120 }),
    ...CAN_CU(),
    cuongChe
      ? P("Căn cứ Quyết định số {qd_kiem_dem_so} ngày {qd_kiem_dem_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về việc kiểm đếm bắt buộc;", { nghieng: true })
      : P("Căn cứ Thông báo thu hồi đất số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa};", { nghieng: true }),
    P("Xét đề nghị của {ten_phong} tại Tờ trình số {to_trinh_so} ngày {to_trinh_ngay}.", { nghieng: true }),
    giua("QUYẾT ĐỊNH:", { dam: true, truoc: 120 }),
    P(`**Điều 1.** Áp dụng biện pháp ${cuongChe ? "cưỡng chế thực hiện quyết định kiểm đếm bắt buộc" : "kiểm đếm bắt buộc"} đối với trường hợp sau:`),
    P("- Tên tổ chức/Họ và tên: {ho_ten};"),
    P("- Địa chỉ thường trú: {dia_chi};"),
    P("- Địa chỉ nơi ở hiện nay: {dia_chi_hien_nay};"),
    P("- Số điện thoại: {dien_thoai};"),
    P("- Diện tích đất dự kiến thu hồi: {dt_thu_hoi} m², thuộc {thua_mo_ta}, tại {ten_xa};"),
    P("- Lý do: {ly_do}."),
    P(`Thời gian thực hiện ${cuongChe ? "cưỡng chế " : ""}kiểm đếm bắt buộc từ ngày {tg_tu} đến ngày {tg_den}.`),
    P("**Điều 2.**"),
    P("1. Quyết định này có hiệu lực kể từ ngày {ngay_hieu_luc}."),
    P("2. {ten_phong} có trách nhiệm giao quyết định này cho {ho_ten} và niêm yết công khai quyết định này tại trụ sở Ủy ban nhân dân {ten_xa}, địa điểm sinh hoạt chung của khu dân cư {ban_khu_dan_cu}."),
    P(`3. Giao {co_quan_thuc_hien} triển khai thực hiện ${cuongChe ? "cưỡng chế " : ""}kiểm đếm bắt buộc theo quy định của pháp luật.`),
    ...(cuongChe ? [P("4. Kinh phí phục vụ thực hiện cưỡng chế: {kinh_phi_cuong_che}.")] : []),
    P(`${cuongChe ? 5 : 4}. {co_quan_thi_hanh} và {ho_ten} chịu trách nhiệm thi hành Quyết định này./.`),
    kyVanBan(),
  ];
}

function niemYet(ketThuc) {
  return [
    ...quocHieu({ ngay: true }),
    ...tenVanBan(
      "BIÊN BẢN",
      ketThuc
        ? "Về việc kết thúc niêm yết công khai phương án bồi thường, hỗ trợ và tái định cư\nkhi Nhà nước thu hồi đất thực hiện dự án {ten_du_an}"
        : "Về việc niêm yết công khai phương án bồi thường, hỗ trợ và tái định cư\nkhi Nhà nước thu hồi đất thực hiện dự án {ten_du_an}",
    ),
    P("Căn cứ Thông báo thu hồi đất số {tb_thu_hoi_so} ngày {tb_thu_hoi_ngay} của Chủ tịch Ủy ban nhân dân {ten_xa} về thu hồi đất để thực hiện dự án {ten_du_an};", { nghieng: true, truoc: 120 }),
    P(`Hôm nay, vào hồi {thoi_diem}, tại {dia_diem_lam_viec}, {ten_don_vi_bt} phối hợp với Ủy ban nhân dân {ten_xa} tổ chức ${ketThuc ? "kết thúc " : ""}niêm yết công khai phương án bồi thường, hỗ trợ và tái định cư khi Nhà nước thu hồi đất thực hiện dự án {ten_du_an}.`),
    P("**I. THÀNH PHẦN**"),
    ...thanhPhan([
      ...TP_DAY_DU,
      ["Đại diện người có đất đai, tài sản gắn liền với đất, người có quyền lợi, nghĩa vụ liên quan được mời chứng kiến:", "tp_nguoi_co_dat"],
      ["Các thành phần khác có liên quan (nếu có):", "tp_khac"],
    ]),
    P("**II. NỘI DUNG**"),
    P("Việc niêm yết công khai dự thảo phương án bồi thường, hỗ trợ và tái định cư dự án {ten_du_an} được thực hiện như sau:"),
    P(`1. Thời gian niêm yết công khai${ketThuc ? " thực tế" : ""}: từ {tg_niem_yet_tu} đến {tg_niem_yet_den} (thời hạn niêm yết 30 ngày theo điểm a khoản 3 Điều 87 Luật Đất đai).`),
    P("2. Địa điểm niêm yết: {dia_diem_niem_yet}."),
    ...(ketThuc
      ? [P("3. Trong thời gian niêm yết công khai đã nhận được các ý kiến kiến nghị, tham gia như sau: {y_kien}.")]
      : [P("3. Đồng thời với việc niêm yết công khai, phương án bồi thường, hỗ trợ và tái định cư được thông báo {so_lan_thong_bao} lần trong thời gian {so_ngay_thong_bao} ngày liên tục (từ ngày {tg_thong_bao_tu} đến ngày {tg_thong_bao_den}) trên hệ thống loa truyền thanh của {ban_khu_dan_cu}.")]),
    KET_BB(),
    kyBienBan(KY_DAY_DU),
  ];
}

/** Nội dung phương án dùng chung cho Mẫu 11, 13, 14. */
function noiDungPhuongAn({ cho }) {
  const out = [
    P("**1. Tổng diện tích đất thu hồi:** {tong_dt_thu_hoi} m², trong đó diện tích từng loại đất thu hồi như sau:"),
    ...lap("dt_theo_loai", "- {loai}: {dien_tich} m²;", { trai: 567, thut: 0, sau: 40 }),
    P("**2. Tổng số đối tượng có đất thu hồi:** {so_doi_tuong} đối tượng. Trong đó gồm: tổ chức {so_to_chuc}; hộ gia đình, cá nhân {so_ca_nhan}."),
    P("**3. Địa điểm:** {dia_diem_du_an}."),
    P("**4. Phương án đào tạo, chuyển đổi nghề và tìm kiếm việc làm (nếu có):** {pa_chuyen_doi_nghe}."),
    P("**5. Phương án bố trí tái định cư (nếu có):** {pa_tai_dinh_cu}."),
    P("**6. Phương án bồi thường bằng đất (nếu có):** {pa_boi_thuong_dat}."),
    P("**7. Phương án di dời mồ mả trong phạm vi đất thu hồi (nếu có):** {pa_mo_ma}."),
    P("**8. Phương án di chuyển các công trình hạ tầng trong phạm vi đất thu hồi (nếu có):** {pa_ha_tang}."),
    P("**9. Kinh phí bồi thường, hỗ trợ, tái định cư**"),
    P("Tổng giá trị phương án: **{tong_gia_tri}** đồng (bằng chữ: {tong_gia_tri_chu}). Trong đó:"),
    P("9.1. Tiền bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất: {tien_bthttdc} đồng (bằng chữ: {tien_bthttdc_chu}), gồm:"),
    P("a) Kinh phí bồi thường về đất: {bt_dat} đồng;", { trai: 567, thut: 0 }),
    P("b) Kinh phí bồi thường hoa màu, tài sản trên đất: {bt_tai_san} đồng;", { trai: 567, thut: 0 }),
    P("c) Kinh phí bồi thường chi phí đầu tư vào đất còn lại (nếu có): {bt_dau_tu_con_lai} đồng;", { trai: 567, thut: 0 }),
    P("d) Các khoản hỗ trợ: {ho_tro} đồng;", { trai: 567, thut: 0 }),
    P("đ) Kinh phí hỗ trợ bàn giao mặt bằng sớm (khuyến khích tiến độ, trường hợp đã xác định được): {ho_tro_ban_giao_som} đồng.", { trai: 567, thut: 0 }),
    P("9.2. Chi phí bảo đảm cho việc tổ chức thực hiện bồi thường, hỗ trợ, tái định cư: {chi_phi_to_chuc} đồng."),
    P("9.3. Các chi phí khác: {chi_phi_khac}."),
    P("**10. Tiến độ thực hiện phương án bồi thường, hỗ trợ, tái định cư:** {tien_do_thuc_hien}."),
    P("**11. Ý kiến, kiến nghị của tổ chức/hộ gia đình/cá nhân về phương án bồi thường, hỗ trợ và tái định cư; kết quả giải quyết (nếu có):** {y_kien_kien_nghi}."),
    P("**12. Các nội dung khác liên quan đến bồi thường, hỗ trợ, tái định cư (nếu có):** {noi_dung_khac}."),
  ];
  return out;
}

const DANH_SACH = [
  ["01", "Thông báo thu hồi đất"],
  ["02", "Thông báo kiểm kê hiện trạng"],
  ["03", "Tờ tự khai"],
  ["04", "Biên bản kiểm kê hiện trạng đất và tài sản trên đất"],
  ["05", "Biên bản tuyên truyền, vận động phối hợp điều tra, kiểm đếm"],
  ["06", "Quyết định kiểm đếm bắt buộc"],
  ["07", "Quyết định cưỡng chế thực hiện quyết định kiểm đếm bắt buộc"],
  ["08", "Biên bản hội nghị lấy ý kiến về phương án"],
  ["09", "Biên bản niêm yết công khai phương án"],
  ["10", "Biên bản kết thúc niêm yết công khai phương án"],
  ["11", "Tờ trình đề nghị thẩm định phương án"],
  ["12", "Tờ trình thu hồi đất"],
  ["13", "Tờ trình đề nghị phê duyệt phương án"],
  ["14", "Quyết định phê duyệt phương án"],
  ["15", "Quyết định thu hồi đất"],
  ["16", "Biên bản giao quyết định"],
  ["17", "Biên bản vận động nhận tiền, bàn giao mặt bằng"],
  ["18", "Thông báo gửi tiền vào tài khoản tiền gửi"],
  ["19", "Biên bản giao Thông báo gửi tiền"],
  ["20", "Tờ trình phê duyệt danh sách hỗ trợ bàn giao mặt bằng sớm"],
  ["21", "Quyết định phê duyệt danh sách hỗ trợ bàn giao mặt bằng sớm"],
  ["22", "Quyết định cưỡng chế thu hồi đất"],
];

for (const [ma, ten] of DANH_SACH) {
  const doc = taoDocument(MAU[ma]());
  const buf = await Packer.toBuffer(doc);
  writeFileSync(new URL(`mau-${ma}.docx`, RA), buf);
  console.log(`Mẫu ${ma}: ${ten} (${buf.length} byte)`);
}
